image: gitpod/workspace-full
tasks:
  - init: yarn install
    command: yarn build
ports:
  - port: 8000
    onOpen: open-browser
github:
  prebuilds:
    master: true
    branches: false
    pullRequests: false
    pullRequestsFromForks: false
    addCheck: false
    addComment: false
    addBadge: false
    addLabel: false
